### PR TITLE
Fix font size vertical rhythm and fix quote and paragraph

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Slight adjustment to the typography in order to match 1:1 editor/email

### How to test the changes in this Pull Request:

1. Create new newsletter
2. Add various paragraphs, headings, quote
3. Play with style, sizes
4. Send a test
5. Switch to this branch
6. Send a new test and compare the result

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
The font sizes are looking consistent! The quote block doesn't look very similar to how I'm seeing in the editor. Feels like the added gray background color calls for a bit more top/bottom padding. WDYT?

| Gutenberg | Rendered Markup |
| --- | --- |
| image | image |

**Comment by thomasguillot** [comment]
> The font sizes are looking consistent! The quote block doesn't look very similar to how I'm seeing in the editor. Feels like the added gray background color calls for a bit more top/bottom padding. WDYT?

Hmmm this is weird... where does the grey background come from? you shouldn't have a background 🤔

**Comment by miguelpeixe** [comment]
Ha, sorry about that. I guess it's coming from the default browser styles. Should we add a default value to avoid this?

**Comment by thomasguillot** [comment]
> Ha, sorry about that. I guess it's coming from the default browser styles. Should we add a default value to avoid this?

Should be fixed with https://github.com/Automattic/newspack-newsletters/pull/725/commits/38d38221225e6bbe8960c3aaf1060202f5c43dbf, would you mind confirming?

**Review by miguelpeixe — APPROVED** [review]
That does it! Thank you! 🎉

**Pull request merged**
