### PR TITLE
feat: preview html

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1205078412187623-as-1205078412187635

Implements HTML preview before sending the newsletter:

### With provider

image

### With "Manual" provider

image

The editor should also be able to change the ad settings or send a test email in this modal screen.

A new "Preview Email" button also renders the HTML in a modal, but without the sending functionality:

image

image

### How to test the changes in this Pull Request:

1. Make sure you have active newsletters ads configured
2. Set your newsletter provider as "Manual" and draft a new newsletter
3. Click "Preview email" and confirm the modal renders with injected ads
4. Close the modal and click to Send
5. Toggle the "Disable automatic insertion of ads" on and confirm it updates the HTML
6. Back to Newsletters settings, change your provider to a supported ESP
7. Repeat steps 3-5
8. Send a test newsletter and confirm you receive the expected content
9. Send the newsletter and confirm you receive the expected content

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — APPROVED** [review]
Works as described.

The one thing I noticed, that might be treated as an improvement, is the lack of user feedback.

When you open the preview modal, it takes a very long time to load the preview, because it's saving the draft and performing other requests, but there's no feedback.

When you send a test, the same thing happens, and also the Success message saying that the test was sent is hidden behind the modal.

Many times an auto-save would happen right after the preview loaded, or after I changed the ads settings, and then I would have to wait twice...

I haven't tested, but I suppose that error messages will also be hidden behind the modal

**Comment by miguelpeixe** [comment]
Thanks for the review and suggestions! Some updates:

- d487fbc61a2559643bf35a07f416121b7b8c2dc1 prevents the spinner from taking over on autosaves.
- b8d2bf307f28c8f9412106b6f8acbe805d44dad7 implements the support of the API response being rendered inline instead of the editor notification

**Review by leogermani — APPROVED** [review]
Looks good, thanks for the improvements.

Not for now, but what do you think of adding the same sidebar that allows for sending test emails to the Preview email modal as well?

**Comment by miguelpeixe** [comment]
Thanks!

> Not for now, but what do you think of adding the same sidebar that allows for sending test emails to the Preview email modal as well?

**Pull request merged**
