### PR TITLE
feat(mailchimp): support double opt-in subscription

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

image

Implements Mailchimp's double opt-in support in the Newsletters Subscription Form block.

Also implements an improvement to the `add_contact` logic to prevent the same execution from adding the contact twice. This can happen with RAS's optimistic way of updating ESP data. It doesn't communicate well with Mailchimp's double opt-in because the API handles a "pending" contact differently. For that reason, we need to prevent this double run.

### How to test the changes in this Pull Request:

1. Check out this branch and make sure you have a Mailchimp setup
2. Add a Newsletters Subscription Form block to a page and confirm you see the new panel as above
3. Without checking the box, save the page
4. Visit the page and subscribe a new email to multiple lists
5. Confirm in Mailchimp's dashboard that the contact is subscribed to all lists
6. Edit the block and check the "double opt-in" option
7. Visit the page and subscribe another email
8. Confirm the contact is not added yet and you receive a confirmation email from Mailchimp
9. Click the email link and confirm the contact is subscribed

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — COMMENTED** [review]
Not working for me... When I enable the Opt-in checkbox, the contacts are not added to Mailchimp at all. (even though the block shows a success message)

any tips?

**Comment by miguelpeixe** [comment]
I don't think pending contacts are listed, you should receive a confirmation email though.

**Comment by leogermani** [comment]
> I don't think pending contacts are listed, you should receive a confirmation email though.
> 
> From the instructions:
> 
> > Confirm the contact is not added yet and you receive a confirmation email from Mailchimp

Yeah, but I'm not getting any email. Will try again shortly

**Comment by leogermani** [comment]
It took a while but the message eventually came in!

**Review by leogermani — APPROVED** [review]

**Pull request merged**
