### PR TITLE
fix: updating a list member

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes a bug. `PATCH` will only update, but `PUT` [will update or create](https://mailchimp.com/developer/marketing/api/list-merges/).

### How to test the changes in this Pull Request:

1. Set up MC w/ two audiences
2. Using Reader Activation, register and subscribe to both lists
3. On `master`, the reader will be subscribed to only the first list, on this branch to both

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
We should either use the `get_contact_data()` method to appropriately identify which lists the contact exists or always upsert regardless of "found subscribers".

The current fix can be misleading for future debugging.

I believe using our contact data method with our own upsertion strategy (instead of `put`) is better because it gives us more control over how it's done. See `update_contact_lists()` for patching subscription status.

**Comment by adekbadek** [comment]
@miguelpeixe  – done in 43236fa660b750a2edf6898713caee18c1db5cdf. I think using `PUT` here is fine – `add_contact` should just upsert, it does not need to be concerned about the payload (which lists to assign/unassign the contact to/from).

**Review by miguelpeixe — APPROVED** [review]
If we're using `PUT`, we shouldn't care for `$existing_contact` to use `POST`. The current detection of existing contact only tells that the email exists in a list. Each list is its own database. Although it works, we're misusing the logic here.

I'm approving because it's non-blocking, but I think we should use a more strict logic to avoid confusion in the future.

**Comment by adekbadek** [comment]
> If we're using PUT, we shouldn't care for $existing_contact to use POST. […] I think we should use a more strict logic  […] Either by using only PUT […]

That's not possible – the `PUT` call requires a contact identifier. It's an upsertion of contact-list pair, not of a contact, so to speak.

> Each list is its own database.

I wouldn't describe it so in the context of these two API calls here. There's a single DB of contacts, each of which can be assigned to list(s) – that would be my description. The logic fixed by this PR deals with either inserting (`POST`) or updating (`PUT`) a contact. The structure of the API endpoints suggests something else, but that's effectively what it does.

**Pull request merged**
