### PR TITLE
fix: let the exceptions be thrown

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

See https://github.com/Automattic/newspack-newsletters/pull/1690#pullrequestreview-2424810964

This PR reverts https://github.com/Automattic/newspack-newsletters/pull/1636

The pattern we use in Newsletters is not something we use in other plugins and we keep forgetting about it.

The pattern is that instead of returning errors, the methods will throw exceptions that we need to catch. This is the basis of the `validate` method so I followed the same thing for the whole Mailchimp Cache class.

In #1636, we are supressing this errors, and the result is that they are not being surfaced when they should.

The thing that we were solving in #1636 was not an issue, it was expected behavior, you can see by the methods doc blocks that they are expected to throw.

### How to test the changes in this Pull Request:

Smoke test

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
Hmm, on this branch after changing the Mailchimp API key to something invalid and refreshing the cache, I don't see any errors in the Settings page after the `SURFACE_ERRORS_AFTER` amount of time has passed. I also see some warnings in the debug log that seem related:

```
[11-Nov-2024 23:14:17 UTC] PHP Warning:  Undefined array key "lists" in /newspack-repos/newspack-newsletters/includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-cached-data.php on line 542
[11-Nov-2024 23:14:17 UTC] PHP Warning:  Undefined array key "lists" in /newspack-repos/newspack-newsletters/includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp-cached-data.php on line 546
[11-Nov-2024 23:14:17 UTC] PHP Warning:  foreach() argument must be of type array|object, null given in /newspack-repos/newspack-newsletters/includes/service-providers/mailchimp/class-newspack-newsletters-mailchimp.php on line 629
```

> The pattern we use in Newsletters is not something we use in other plugins and we keep forgetting about it.
> 
> The pattern is that instead of returning errors, the methods will throw exceptions that we need to catch. This is the basis of the `validate` method so I followed the same thing for the whole Mailchimp Cache class.

I wonder if we should retain this pattern since it keeps breaking our brains? Could we refactor the `validate` method to use `WP_Error`s instead of exceptions that we need to catch and handle manually? Maybe outside the scope of this PR, but I feel this pattern has anecdotally bitten us more than helped us.

**Comment by leogermani** [comment]
@dkoo  I can't reproduce what you described. This branch was outdated, so it might have contributed.

Here is what I see:

* Having a healthy connection
* I change the mailchimp api key to an invalid one
* I see the error right away (because the cache is invalidated)
* I go to line 304 and comment the `if` out, so the errors are stored right away
* trigger the cron to refresh the cache (`wp cron event run newspack_nl_mailchimp_refresh_cache`)
* I see that persistent error alert in all pages

Also, I noticed that we were never clearing the `lists` error. Fixed in https://github.com/Automattic/newspack-newsletters/pull/1698/commits/e0c700ba259bd3275334824ff8ec341376f0f53c

**Comment by leogermani** [comment]
> I wonder if we should retain this pattern since it keeps breaking our brains? Could we refactor the validate method to use WP_Errors instead of exceptions that we need to catch and handle manually? Maybe outside the scope of this PR, but I feel this pattern has anecdotally bitten us more than helped us.

ah, and about this. You're probably right. We should use a pattern we use everywhere else... but I personally don't want to engage in this refactor right now :)

**Review by dkoo — APPROVED** [review]
This is working for me after the refresh. Thanks, @leogermani!

**Pull request merged**
