### PR TITLE
Add branding banner to the CPT wp-admin pages

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Very simple Newspack banner added to the CPT page using CSS-only as I didn't want to tweak the PHP of the pages.

Screenshot 2020-08-27 at 17 16 33

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Do you see the blue banner when visiting the different sections of the plugin (All Newsletters, Settings, Ads)
3. Try to install the plugin for the first time (no Settings). Does it clash with our dismissible banner?

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — COMMENTED** [review]
Shouldn't it link to newspack.pub?

**Comment by thomasguillot** [comment]
> Shouldn't it link to newspack.pub?

@adekbadek we could but it would require more than just some CSS and I'm not sure if it's worth it.

**Comment by adekbadek** [comment]
I think it is :) Here's a proposition: 8cb01cb9d6be1e073e243c11fa9f878ddee2fa75

**Comment by thomasguillot** [comment]
> I think it is :) Here's a proposition: [8cb01cb](https://github.com/Automattic/newspack-newsletters/commit/8cb01cb9d6be1e073e243c11fa9f878ddee2fa75)

Fair enough 😄

**Review by adekbadek — APPROVED** [review]
Assuming approval for my part from @thomasguillot :D

**Pull request merged**
