### PR TITLE
feat: tracking settings

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

1205078412187623-as-1205085335040733

Implements toggling the tracking features.

image

### How to test the changes in this Pull Request:

1. Check out this branch and visit Newsletters -> Tracking
2. Confirm you see the options toggled on by default
3. Create and send a newsletter with links
4. Confirm the links are proxied and the tracking pixel is also present
5. Visit the Tracking settings again, toggle both off and save
6. Visit the Newsletters table and confirm the "Opened" and "Clicks" columns don't render
7. Send another newsletter with links and confirm the URLs are not proxied and the pixel is not present

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — CHANGES_REQUESTED** [review]
Everything works as expected but I have two request/suggestions

1. The rewrite rule flush, for some reason, didn't work for me. The option was created and everything, but I had to manually run a rewrite flush to make links work.

Perhaps we could check if the rules are updated in the settings page and, if not, display a button to refresh the rules. (or automatically do it only on that page, but checking for the rules itself instead of an option?)

2. For readability and maintainability I think we could add a `is_tracking_pixel_enabled` and `is_tracking_click_enabled` methods to the admin class (or other class) and use this instead of having to call `get_option` with `true` as the default value everywhere. Not only we don't have to repeat the option name everywhere, but also we have the logic that considers `true` the default value in only one place, documented. wdyt?

**Comment by leogermani** [comment]
Another idea I had here was to make the settings disable by default and flush rewrite rules when saving the settings for the first time

**Comment by miguelpeixe** [comment]
Thank you for the review and suggestions!

- b5da53bf1f752c350079b56d4d5976f9833ac311: added the helper method
- e71df8aa34ca8e114c42773d90ea4a6165273791: implements rewrite rules flush on settings update
- d56e8404300a8c342bcf89da5f00165eac308216: tweaks the setting field to have a label element so it toggles the checkbox on the label click

> Another idea I had here was to make the settings disable by default and flush rewrite rules when saving the settings for the first time

That would change how we want the feature to work. I believe you experienced an edge case. If you switch to a branch without this feature and the rewrite rules are flushed, it won't flush again once you change back to this branch because the option was already stored in the db. This is not expected to happen live.

**Review by leogermani — APPROVED** [review]
Now I see that the rewrite rules were there already.

Can I just ask something? Use `add_option` instead of `update_option` to set the flags to avoid that annoying cache bug?

**Comment by miguelpeixe** [comment]
Thanks! Good call, done in 46ec6dae89371b8fedf9149f2889266e3b38915c

**Pull request merged**
