### PR TITLE
Allow constant contact to send to segments

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Allow users to send Newsletters to Segments using Constant Contact provider

### How to test the changes in this Pull Request:

1. Set Constant Contact as the provider with proper credentials
2. Create a new Newsletter
3. Verify the UI on the Sidebar Newsletter settings where you select the option to "SEND TO"
4. If you select one or more Lists, the Segments Select should be emptied
5. If you select one Segment, the Lists should all be unchecked
6. Play with these changes and verify that the Campaign in the Constant Contact dashboard is being updated with the correct values
7. Change the value on the CC dashboard and refresh the editor. Verify that the new values are correctly set up

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
This works well as described and I don't see any issues with the code. However, I find the UI to be a bit confusing. Since lists and segments are mutually exclusive, could we implement something closer to what we have for Campaign Monitor (which shares the same restriction)?

The UI lets you select either lists or segments:

Screen Shot 2022-12-22 at 2 55 36 PM

Only after selecting an option do you see the fields to choose a list or segment:

Screen Shot 2022-12-22 at 2 55 44 PM
Screen Shot 2022-12-22 at 2 55 52 PM

I also feel like the control used to display and select lists vs. segments should be the same. I feel like `SelectControl` would be appropriate for lists rather than checkboxes.

cc @thomasguillot

**Comment by leogermani** [comment]
> could we implement something closer to what we have for Campaign Monitor (which shares the same restriction)?

Sure, that's a good idea. Will do.

> I also feel like the control used to display and select lists vs. segments should be the same. I feel like SelectControl would be appropriate for lists rather than checkboxes.

Constant Contact allows you to send campaigns to more than one list. If we did that we would remove that possibility that the ESP offers.

**Comment by leogermani** [comment]
I have added the Send Mode selection in the same way we do in Campaign Monitor

Captura de tela de 2022-12-23 15-14-04

I've left the Lists as checkboxes because, as I said, the provider allows that (and that's how it currently is presented, so removing this would degrade the experience).

I added a wrapper to limit the height and add a scrollbar in case there are too many lists:

Captura de tela de 2022-12-23 15-25-39

**Comment by thomasguillot** [comment]
Dialog

Could we change the "send mode" to a `ButtonGroup` instead, with List being selected by default?
Also, I don't think we need the labels.

**Comment by dkoo** [comment]
@leogermani thanks for clarifying about CC being able to send to multiple lists at once. I think @thomasguillot's proposed UI looks good—could we implement that?

**Comment by leogermani** [comment]
Thanks @thomasguillot for looking at this. It looks much better

Captura de tela de 2023-01-09 16-09-20
Captura de tela de 2023-01-09 16-09-26

One little thing. The default style of the component leaves the label text for the secondary button blue, and not black. Is it ok or should we override it?

**Comment by thomasguillot** [comment]
@leogermani thank you for the changes 😍
I think it'd look better if we could have the text and the border to use `$gray-900`

**Comment by leogermani** [comment]
@thomasguillot done in https://github.com/Automattic/newspack-newsletters/pull/1055/commits/dc1bda8030dadf46d90a2d9211255ddab9e04275!

Captura de tela de 2023-01-09 19-47-36

**Review by dkoo — APPROVED** [review]
The new UI looks great and is much clearer to me!

**Pull request merged**
