### PR TITLE
Add block support for Site Logo, Site Tagline, and Site Title

### LINKED ISSUE #646: Blocks: Support Site Logo and Site Title
At the moment we are using custom code to import the Site Logo (or Site Title) to the Newsletter.

Ideally we should be using Core's Site Logo and Site Title blocks (from FSE, without the ability to edit the logo/title)

### PR DESCRIPTION
**Pull request by thomasguillot**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Instead of using a hack to display the Site Logo or Site Title throughout the default layouts, this PR adds support for Core's Site Logo, Site Tagline, and Site Title.

Closes #646 .

### How to test the changes in this Pull Request:

1. Switch to this branch
2. Make sure your site has a Site Logo
3. Create a new newsletter
4. You should see your logo in the preview
5. Add any default layouts
6. In the editor you should see the "Site Logo" block
7. Send a test email and check if everything is being displayed correctly
8. Go to the customiser and remove your Site Logo
9. Create a new newsletter
10. You should see your site title in the preview
11. Add any default layouts
12. In the editor you should see the "Site Title" block
13. Add the "Site Tagline" block
14. Send a test email and check if everything is being displayed correctly
15. Send and Publish the Newsletter
16. Check the web version

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by miguelpeixe** [comment]
@thomasguillot I've synced the branch with master and implemented the rendering of the new blocks through MJML on c2c8adad020899dc4d184d3941028b701f262415.

Can you confirm the rendering is working as expected and let me know if there's anything missing?

**Comment by miguelpeixe** [comment]
Also, it would be interesting to have the "Site logo" blocks on the layouts with `{ "newsletterVisibility": "email" }` by default so it is automatically set to not display on the web version. WDYT?

**Comment by thomasguillot** [comment]
> Also, it would be interesting to have the "Site logo" blocks on the layouts with `{ "newsletterVisibility": "email" }` by default so it is automatically set to not display on the web version. WDYT?

I thought about this, and yes, I agree. The only thing is, you get an "error" message when the newsletter isn't set to public. Which means by default the user would see this message.

I wonder if we should remove the message.

**Comment by miguelpeixe** [comment]
> The only thing is, you get an "error" message when the newsletter isn't set to public. Which means by default the user would see this message.

The "error" message should only appear if the block is set to "web" and the newsletter is not set to have a web version. It shouldn't be the case if it's set to "email". Are you seeing any error message in this case?

**Comment by thomasguillot** [comment]
> The "error" message should only appear if the block is set to "web" and the newsletter is not set to have a web version. It shouldn't be the case if it's set to "email". Are you seeing any error message in this case?
> 
> Once the newsletter is set to have a web version, a warning message appears for either case (if its set to web or email only).

Oh yeah, that's right! (done in https://github.com/Automattic/newspack-newsletters/pull/679/commits/67e7dedb26deab5c81712aee7f27a0a56b45469b)

Screenshot 2022-02-04 at 21 18 19

I guess what bothers me here is the icon is visible and I can toggle the visiblity.

**Comment by thomasguillot** [comment]
Re: site logo, we don't need all the options like Duotone, Crop, Replace, Use as site icon, or even the "Rounded" style

**Comment by miguelpeixe** [comment]
Since duotone is a featured for any image type block and is not supported by Newsletters, I've submitted #732 for it.

It's unlikely that we'll be able to remove "crop", "replace", "Use as site icon" and custom styles features without rewriting the block settings. I'm not sure if we should take that route.

**Comment by thomasguillot** [comment]
> Since duotone is a feature for any image type block and is not supported by Newsletters, I've submitted #732 for it.

Nice! 🥳 

> It's unlikely that we'll be able to remove "crop", "replace", "Use as site icon" and custom styles features without rewriting the block settings. I'm not sure if we should take that route.

Ok 👍

**Comment by thomasguillot** [comment]
> I guess what bothers me here is the icon is visible and I can toggle the visiblity.

Done in #733

**Review by miguelpeixe — APPROVED** [review]
👌

**Pull request merged**
