### PR TITLE
API Key Modal

### PR DESCRIPTION
**Pull request by jeffersonrabb**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Adds a first screen to the Template Picker modal where users input the API keys needed to use the plugin (Mailchimp and MJML). 

- Refactor of the template picker to support multiple screens. Also refactored using React Hooks.
- New endpoints to get and set the API keys: `newspack-newsletters/v1/keys` GET|POST
- When keys are set they are also verified by pinging the services. 

Notes for @thomasguillot: 
- To avoid confusion I've left this completely un-styled. 
- I used `Spinner` components to show the In-Flight state, but these are ugly and poorly placed. I suspect you'll have a different idea about this state anyway, so I put them in just to demonstrate how to detect the state.
- I included error messages for Mailchimp and MJML if the keys are empty or invalid. I assume you'll also want to handle these differently.

Closes https://github.com/Automattic/newspack-newsletters/issues/52
Closes https://github.com/Automattic/newspack-newsletters/issues/82

### Screenshots
<details>
Screen Shot 2020-04-19 at 9 06 45 AM
Screen Shot 2020-04-19 at 9 07 22 AM
</details>

### How to test the changes in this Pull Request:

1. Go to Settings->Newspack Newsletters and clear out all three keys. 
2. Create a new Newsletter, observe the API Keys modal screen.
3. Try submitting with various combinations of blank fields, valid keys, and invalid keys. Verify the relevancy of the error messages displayed in each case.
4. Try submitting valid keys in all three fields. Verify the modal switches to the Template Picker. In Settings->Newspack Newsletters verify the keys have been set correctly.
5. Try submitting fields by clicking the blue button as well as pressing ENTER while in a text input.
6. After keys have been set, create a new Newsletter and observe the Template Picker is displayed, not the API Key screen.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by thomasguillot** [comment]
Tweaked the styles in https://github.com/Automattic/newspack-newsletters/pull/74/commits/35a156f015be1d9916297ca74209cf8d8464a2ed

@jeffersonrabb any chance we can separate the error messages for MJML since we have 2 fields?

**Comment by adekbadek** [comment]
@thomasguillot MJML key & secret work as a pair, it's not possible to validate one without the other

**Comment by thomasguillot** [comment]
@jeffersonrabb in https://github.com/Automattic/newspack-newsletters/pull/74/commits/0cc6d5db4f111ee2f64443bc07eb6d9711fb42c8 I've slightly moved the modal so it shows the close/back button so you will probably want to re-review/test this PR.

Screenshot 2020-04-20 at 18 05 43

**Comment by jeffersonrabb** [comment]
> @jeffersonrabb in [0cc6d5d](https://github.com/Automattic/newspack-newsletters/commit/0cc6d5db4f111ee2f64443bc07eb6d9711fb42c8) I've slightly moved the modal so it shows the close/back button so you will probably want to re-review/test this PR.

Hmmm, I'm not seeing the close/back button:

Screen Shot 2020-04-20 at 1 54 04 PM

**Comment by thomasguillot** [comment]
> Hmmm, I'm not seeing the close/back button:

It's because you're not in fullscreen mode.

**Pull request merged**
