### PR TITLE
fix: sync newsletter campaigns on post meta update for all ESPs

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

#1526 changed the hook used to sync newsletter posts to the connected ESP to `updated_post_meta`. However, this was erroneously done only for Mailchimp and not the other ESPs.

### How to test the changes in this Pull Request:

1. On `release`, switch your ESP to ~a non-Mailchimp ESP~ Constant Contact.
2. Create a new newsletter and observe a message that never resolves in the sidebar: 

cleanshot_2024-07-03_at_10 51 57_2x

3. Also observe that in the connected Constant Contact account, a synced campaign is never created.
4. Switch your ESP to Active Campaign.
5. Create a new newsletter and edit the content, then save. Observe that in the synced campaign in Active Campaign, the newsletter content is not updated after the save.
6. Check out this branch, switch back to CC, create another new newsletter, and confirm that the campaign syncs correctly for new newsletters. (You can also refresh and save the original newsletter created in step 1 and confirm that it gets synced upon save).
7. Switch to AC, then edit and save the newsletter you created in step 5. Confirm that the synced campaign in AC is updated after saving.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by laurelfulford** [comment]
I tried testing this but I run into issues that I'm not sure are "real" or just me -- adding below as a comment instead of as a review since I'm not confident in them. 

**Constant Contact:**
* The "Retrieving data..." message in the sidebar is gone. 
* When I create a new newsletter, it syncs the initial draft to Constant Contact, but subsequent draft saves don't appear to update it. I'm not sure if this is an issue or not, except...
* When I try to send to a small email list I created, I get an error:

image

Unfortunately it doesn't look like we can send test emails with our CC account, so I can't confirm whether this actually is updating right. 

**MailChimp:**
* Does not show any "Retrieving data..." message.
* When I create a new newsletter, it synced to MC, and subsequent draft saves update it.
* Sending an email to a small group works fine.

**ActiveCampaign:**
* Does not show any "Retrieving data..." message. I noticed I briefly got the spinner in the same area, but it quickly resolved. That issue doesn't appear to happen for AC on release either, though.
* When I create a new newsletter it doesn't seem to sync to AC at all -- it doesn't show up in the Campaigns list, but I'm not sure this is expected.
* Sending an email to a small group works fine. It included my latest changes after making edits and saving the draft a few times, so I suspect the previous bullet point doesn't matter. 

If someone else tests this and doesn't run into the same CC issues, I'm going to chalk that up to a bad day on my part, but the site I tested on can be shared if that would help!

**Comment by dkoo** [comment]
@laurelfulford thanks for testing! I did confirm that our Constant Contact `sync` method was missing the step to rename the synced campaign based on the "Campaign Name" meta value, so I added that in 024e6ed. 

I also was able to confirm that the campaign subject/preview text/body/send to options are updated correctly upon save, and that when sending a test email or a live campaign, the changes I make persist to the sent email.

> When I create a new newsletter it doesn't seem to sync to AC at all -- it doesn't show up in the Campaigns list, but I'm not sure this is expected.

I think this is expected. ActiveCampaign doesn't support updating a campaign via their API once it's been created. So we don't create a campaign in AC until we have to send it (either as a test, or as a live campaign). More details here: #844

**Comment by laurelfulford** [comment]
Thanks for double-checking that, @dkoo! 

I'm still having issues with Constant Contact sending, and updating the email drafts past the newsletter creation 😕 I'm going to try recreating the connection and see if I have more luck!

Edited to add: it's still not working for me. I'm not sure what I'm doing wrong, but if you're able to send emails through Constant Contact, it's most likely something I'm doing wrong.

**Comment by dkoo** [comment]
@laurelfulford  Turns out the `sync` request from your test site was failing with an error message because of a setup issue with the connected CC account, but due to the fact that #1526 triggers the sync as a side effect of a save (and not during the save itself) we're not seeing the error message in the editor. Once I corrected the issue in the CC account, the syncs  started working again.

I think this approach will need to be refined in a future PR, but 224d40d adds some basic error handling to capture error messages from the `sync` requests in a transient which is then loaded and displayed when the editor next loads. This still means the error message won't be displayed until the editor is next refreshed or reloaded, but at least we'll show it somewhere. The transient is cleared the next time a `sync` request is attempted.

To test this, in your test CC account visit Account Settings and edit your business details. Set the ZIP code to something invalid like `11-11` and save, then attempt to save a newsletter from the WP newsletter editor. After 224d40d, when you next refresh the editor you should see an error message like `Constant Contact: Physical Address Postal Code is not in the valid format, please include a valid address postal code (zip code) with this request`

**Review by leogermani — APPROVED** [review]
All works fine. The Campaign only gets created in AC after I send a test email. I believe that's the expected behavior for AC

**Pull request merged**
