### PR TITLE
fix(mailchimp): selecting mailchimp segments with groups

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes a bug where our "Send To" UI can't handle selecting a Mailchimp segment that contains groups.

### How to test the changes in this Pull Request:

1. Connect your site to a Mailchimp account.
2. In Mailchimp, go to **Audience > Segments** and create a new segment. Add at least one filter that relates to group membership, like so:

Screenshot 2024-08-06 at 4 28 02 PM

3. Save the segment.
4. In the Newsletters plugin, create or edit a newsletter. In the **Send To** panel, select your audience and the segment you created in step 2.
5. On `release`, observe that the "Group, Segment, or Tag" dropdown reverts to an unselected state, even though in Mailchimp the synced campaign is correctly set to the segment.
6. Check out this branch and refresh the newsletter editor, and confirm the segment now shows as selected.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207497532448704

### CODE REVIEW

**Comment by dkoo** [comment]
Note to reviewers: I think the CI lint jobs are wigging out due to the current mismatch in dependencies. The errors shown in the failed jobs are not related to any changes in this PR.

**Review by miguelpeixe — CHANGES_REQUESTED** [review]
It seems to fix the issue for segments, but now I'm unable to select groups. Tag selection seems to be working without regressions.

newsletters-PR1600

**Comment by dkoo** [comment]
@miguelpeixe I had a bad paste in the original changeset. 10bce5a should fix it so you can select both segments and groups (and segments that contain groups) as well.

**Review by miguelpeixe — APPROVED** [review]
Thank you for revising! Working well now

**Pull request merged**
