### PR TITLE
fix: use mailchimp as the default ESP

### PR DESCRIPTION
**Pull request by adekbadek**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Closes https://github.com/Automattic/newspack-plugin/issues/1487

### How to test the changes in this Pull Request:

1. Install plugin on a fresh site, visit Settings, observe "Mailchimp" is set as the Service Provider
2. Observe that https://github.com/Automattic/newspack-plugin/issues/1487 is resolved

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1201754873912049

### CODE REVIEW

**Comment by miguelpeixe** [comment]
I don't think the default value for the service provider is related to this issue. On the master branch (without a default provider) the Newsletter wizard is being displayed without issues:

image
 
This is the result for the `wizard/newspack-engagement-wizard/newsletters` endpoint:

```json
{
   "configured":true,
   "settings":{
      "newspack_newsletters_service_provider":{
         "description":"Service Provider",
         "key":"newspack_newsletters_service_provider",
         "options":[
            {
               "name":"Select service provider",
               "value":""
            },
            {
               "name":"Mailchimp",
               "value":"mailchimp"
            },
            {
               "name":"Constant Contact",
               "value":"constant_contact"
            },
            {
               "name":"Campaign Monitor",
               "value":"campaign_monitor"
            },
            {
               "name":"Manual \/ Other",
               "value":"manual"
            }
         ],
         "type":"select",
         "onboarding":true,
         "value":false
      },
      "newspack_mailchimp_api_key":{
         "description":"Mailchimp API Key",
         "key":"newspack_mailchimp_api_key",
         "type":"text",
         "default":"",
         "provider":"mailchimp",
         "placeholder":"123457103961b1f4dc0b2b2fd59c137b-us1",
         "help":"Find or generate your API key",
         "helpURL":"https:\/\/mailchimp.com\/help\/about-api-keys\/#Find_or_generate_your_API_key",
         "onboarding":true,
         "value":false
      },
      "newspack_newsletters_constant_contact_api_key":{
         "description":"Constant Contact API Key",
         "key":"newspack_newsletters_constant_contact_api_key",
         "type":"text",
         "provider":"constant_contact",
         "onboarding":true,
         "value":false
      },
      "newspack_newsletters_constant_contact_api_secret":{
         "description":"Constant Contact API Secret",
         "key":"newspack_newsletters_constant_contact_api_secret",
         "type":"text",
         "provider":"constant_contact",
         "onboarding":true,
         "value":false
      },
      "newspack_newsletters_campaign_monitor_api_key":{
         "description":"Campaign Monitor API Key",
         "key":"newspack_newsletters_campaign_monitor_api_key",
         "type":"text",
         "provider":"campaign_monitor",
         "onboarding":true,
         "value":false
      },
      "newspack_newsletters_campaign_monitor_client_id":{
         "description":"Campaign Monitor Client ID",
         "key":"newspack_newsletters_campaign_monitor_client_id",
         "type":"text",
         "provider":"campaign_monitor",
         "onboarding":true,
         "value":false
      },
      "newspack_newsletters_public_posts_slug":{
         "default":"newsletter",
         "description":"Public Newsletter Posts Slug",
         "key":"newspack_newsletters_public_posts_slug",
         "sanitize_callback":"sanitize_title",
         "type":"text",
         "onboarding":false,
         "value":"newsletter"
      },
      "newspack_newsletters_letterhead_api_key":{
         "default":"",
         "description":"Letterhead API Key",
         "key":"newspack_newsletters_letterhead_api_key",
         "type":"text",
         "help":"Promotions API reference",
         "helpURL":"https:\/\/help.tryletterhead.com\/promotions-api-reference",
         "onboarding":false,
         "value":false
      }
   }
}
```

@dkoo, can you reproduce the issue and share the result of this endpoint? Maybe an unrelated error is being thrown, preventing the component to render.

**Comment by adekbadek** [comment]
The UI on the screenshot is out of date – the latest version enables choosing a provider on setup (https://github.com/Automattic/newspack-plugin/pull/1449):

image

Can you test again while on `master` of `newspack-newsletters` & `newspack-plugin`?

**Comment by miguelpeixe** [comment]
Still working well without a default service provider. 🤔 

https://user-images.githubusercontent.com/820752/152368806-690c02e5-b4ff-4adb-ad1f-445685739533.mov

**Comment by dkoo** [comment]
What I'm seeing in a site when the issue occurs:

```
{
	"configured": true,
	"settings": {
		"newspack_newsletters_service_provider": {
			"description": "Service Provider",
			"key": "newspack_newsletters_service_provider",
			"options": [
				{
					"name": "Select service provider",
					"value": ""
				},
				{
					"name": "Manual",
					"value": "manual"
				},
				{
					"name": "Mailchimp",
					"value": "mailchimp"
				},
				{
					"name": "Constant Contact",
					"value": "constant_contact"
				},
				{
					"name": "Campaign Monitor",
					"value": "campaign_monitor"
				}
			],
			"type": "select",
			"value": false
		},
		"newspack_mailchimp_api_key": {
			"description": "Mailchimp API Key",
			"key": "newspack_mailchimp_api_key",
			"type": "text",
			"default": "",
			"provider": "mailchimp",
			"value": false
		},
		"newspack_newsletters_constant_contact_api_key": {
			"description": "Constant Contact API Key",
			"key": "newspack_newsletters_constant_contact_api_key",
			"type": "text",
			"provider": "constant_contact",
			"value": false
		},
		"newspack_newsletters_constant_contact_api_secret": {
			"description": "Constant Contact API Secret",
			"key": "newspack_newsletters_constant_contact_api_secret",
			"type": "text",
			"provider": "constant_contact",
			"value": false
		},
		"newspack_newsletters_campaign_monitor_api_key": {
			"description": "Campaign Monitor API Key",
			"key": "newspack_newsletters_campaign_monitor_api_key",
			"type": "text",
			"provider": "campaign_monitor",
			"value": false
		},
		"newspack_newsletters_campaign_monitor_client_id": {
			"description": "Campaign Monitor Client ID",
			"key": "newspack_newsletters_campaign_monitor_client_id",
			"type": "text",
			"provider": "campaign_monitor",
			"value": false
		},
		"newspack_newsletters_public_posts_slug": {
			"default": "newsletter",
			"description": "Public Newsletter Posts Slug",
			"key": "newspack_newsletters_public_posts_slug",
			"sanitize_callback": "sanitize_title",
			"type": "text",
			"value": "newsletter"
		},
		"newspack_newsletters_letterhead_api_key": {
			"default": "",
			"description": "<a href=\"https:\/\/tryletterhead.com\" target=\"_blank\">Letterhead<\/a> API Key",
			"key": "newspack_newsletters_letterhead_api_key",
			"type": "text",
			"value": false
		}
	}
}
```

The response is 200, but it's missing the `onboarding` keys.

**Comment by dkoo** [comment]
I think we can classify this as a non-bug. The latest `master` branch of this repo expects the `onboarding` key to exist, from [this PR in Newsletters](https://github.com/Automattic/newspack-newsletters/pull/694). However, that PR hasn't been released yet, so when installing the main plugin from `master`, it's pulling Newsletters code from the last release.

I'm not sure whether we want to keep the Mailchimp-as-default change here, but it won't be necessary after https://github.com/Automattic/newspack-newsletters/pull/694 gets released.

**Review by dkoo — APPROVED** [review]
Approving because it works, but see my comment above.

**Comment by miguelpeixe** [comment]
> I'm not sure whether we want to keep the Mailchimp-as-default change here

We were to have a default provider, I'd vote for the agnostic "manual/other" option.

**Comment by dkoo** [comment]
> If we were to have a default provider, I'd vote for the agnostic "manual/other" option.

This makes sense, or just keeping no default to force the user to choose one.

**Comment by adekbadek** [comment]
Thank you both for the input! I think we can close this and not suggest a default provider if there is no consensus about which one should it be.

**Pull request closed without merging**
