### PR TITLE
fix: parse legacy layout defaults

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR parses legacy `newsletterData` metadata on preexisting custom newsletter layouts to migrate sender and send-to settings to the newer, leaner, cross-ESP-compatible `campaign_defaults` meta field for layout CPT posts. This should make #1658 NOT a breaking change, as publishers' preexisting custom layouts will be able to seamlessly their data.

### How to test the changes in this Pull Request:

1. On `trunk` or `release`, create a new newsletter, set sender email + name and list/sublist options, then save as a new custom layout.
2. Check out this branch, then create a new newsletter using the custom layout from step 1. Confirm that the Sender Name/Email and Send To options are prepopulated from the layout settings.
3. Repeat for Mailchimp, ActiveCampaign, and ~Constant Contact~ (Campaign Monitor is not handled as there is no preexisting legacy data to handle for this ESP). EDIT: also, Constant Contact does not seem to work as creating a new campaign always seems to set the top-level list by default, but this is also the case in `trunk`, so I think this is non-blocking for now.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — CHANGES_REQUESTED** [review]
WFM with Mailchimp, but not with AC – the list was saved, but the sender not:

image

**Comment by dkoo** [comment]
@adekbadek good catch, I had a mistake with the `senderName` meta field name for the AC method, plus the legacy `newsletterData` has a different shape for AC vs. the other ESPs. c567728 should fix both issues.

**Review by adekbadek — APPROVED** [review]
Works as expected, but I see file changes – changelog, package.json, etc – which should not be part of this PR. Pre-approving, but these should be removed.

**Comment by dkoo** [comment]
Whoops, that's because I had updated `epic/update-editor-uis` locally but forgot to push. Should be good now, thanks!

**Pull request merged**
