### PR TITLE
feat: ads taxonomies and fields

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

image

Implements the following new tax and meta fields for Newsletter Ads:
 - Start date field
 - Price field
 - Advertisers taxonomy
 - Categories taxonomy (same as posts/newsletters)

The taxonomies determine the following:
1. Newsletters associated with an advertiser should only render ads that are also associated with that same advertiser
2. Ads associated with a category should only be rendered in newsletters that are also associated with that category

That means newsletters without any advertiser association can render ads from any advertiser. That also means that ads without any categories can be rendered on any newsletter.

### How to test the changes in this Pull Request:

1. Check out this branch and create an ad with a future start date
2. Draft a new newsletter, save, click to preview, and confirm the ad doesn't render
3. Edit the ad and toggle "Custom Start Date"
4. Don't click any date, the starting date is today and should be disabled for selection (just like past dates)
5. Save, edit the newsletter, and preview
6. Confirm the ad renders
7. Edit the ad, set a future start date, and toggle the "Expiration Date"
8. Confirm you can't select a date prior to the start date
9. Select a future date, set a price, and save
10. Refresh and confirm the values persisted
11. Untoggle the Custom Start Date and save
12. Edit the newsletter, save, preview, and confirm you the ad renders
13. Edit the ad and attach it to an existing category and a new advertiser
14. Edit the newsletter, save, preview, and confirm the ad doesn't render
15. Set the category to the newsletter, save, preview, and confirm the ad renders
16. Set a different new advertiser, save, preview, and confirm the ad doesn't render

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — APPROVED** [review]
Working as described. Just confirming, a future publish date and a custom start date are equivalent? Or is there a difference that should be explained to publishers? One minor thing to note is that it's currently possible to set an expiration date before a future publish date.

**Comment by miguelpeixe** [comment]
> Just confirming, a future publish date and a custom start date are equivalent?

They're not! 2391876426d3b48e10abb52f58f641afd7362005 removes the "Summary" sidebar panel to avoid confusion and changes the component to use hooks instead of HoCs.

> One minor thing to note is that it's currently possible to set an expiration date before a future publish date.

Should be possible if you first select the expiration date and later set a later start date. If that's the case you should get this notice before publishing:

image

**Review by dkoo — CHANGES_REQUESTED** [review]
A lingering old constant name that needs updating:

```
PHP Fatal error:  Uncaught Error: Undefined constant Newspack_Newsletters_Ads::NEWSPACK_NEWSLETTERS_ADS_CPT in /newspack-repos/newspack-newsletters/includes/class-newspack-newsletters-ads.php:65
```

Otherwise, removing the Summary panel from the newsletter ads editor helps eliminate the confusion around future pub dates vs. custom start dates. Thanks!

**Comment by miguelpeixe** [comment]
Whoops, poor rebasing 😬 

Should be ok now.

**Review by dkoo — APPROVED** [review]
Working now!

**Pull request merged**
