### PR TITLE
feat: send verification email upon new account registration

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Along with https://github.com/Automattic/newspack-plugin/pull/1876, sends a verification email instead of the standard WooCommerce "welcome" email to readers who register a new account via direct email input.

Will not send a verification email to readers who register via SSO, which is considered a secure login method and doesn't require verification.

Closes https://github.com/Automattic/newspack-plugin/issues/1872.

### How to test the changes in this Pull Request:

1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1876.
2. Register a new email address via the Register block (via direct email input, not SSO) and confirm that you receive a verification email (with slightly tweaked language) instead of WooCommerce's "Your Newspack account has been created!" email.
3. Visit the verification URL in the same session where you registered the email address and confirm that you're redirected to the main My Account dashboard page with a message that your email has been verified. Also confirm that you're able to manage newsletter subscriptions at this point.
4. In a new session, register a new account via SSO and confirm that you do not receive a verification email, and that you're immediately able to manage newsletter subscriptions in My Account > Newsletters.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by miguelpeixe** [comment]
If we're disabling WC welcome email and replacing it with our own RAS email, I think this should be considered a core feature and be included in `newspack-plugin`, not newsletters. WDYT?

**Comment by dkoo** [comment]
> If we're disabling WC welcome email and replacing it with our own RAS email, I think this should be considered a core feature and be included in `newspack-plugin`, not newsletters. WDYT?

I thought the same, but opted for the smaller changeset at first. 😄 I'll refactor to move most of this functionality to the main plugin.

**Comment by miguelpeixe** [comment]
Considering that newsletters picks up the `newspack_reader_verified` action hook, we don't need to use newsletters feature for this. Sending a RAS' magic link should be enough for verification as well.

**Comment by miguelpeixe** [comment]
We must still preserve newsletters' agnostic verification for 2 reasons:

 - It should be able to work stand-alone
 - It per-email basis. Once RAS start supporting email address updates newsletters must still have its own verification strategy to not allow an email change access subscriptions

**Comment by dkoo** [comment]
afbae2d moves all email verification methods to the main plugin.

> Considering that newsletters picks up the `newspack_reader_verified` action hook, we don't need to use newsletters feature for this. Sending a RAS' magic link should be enough for verification as well.

I like the idea of keeping a separate verification flow so that we can use different messaging in each case. As a reader, it doesn't make a ton of sense to me to receive a magic "authentication" link after registering a new account and being authenticated on the site.

**Comment by miguelpeixe** [comment]
> As a reader, it doesn't make a ton of sense to me to receive a magic "authentication" link after registering a new account and being authenticated on the site.

The magic link is just the URL strategy for verifying. The email message is what tells the reader what the link does.

**Comment by dkoo** [comment]
I think I know what to do here, then.

**Comment by dkoo** [comment]
Closing this PR as it's no longer needed—we'll use magic links instead.

**Pull request closed without merging**
