### PR TITLE
feat: Newspack Sponsors integration

### PR DESCRIPTION
**Pull request by dkoo**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Replaces #1260 because for some strange reason that PR wouldn't update when I pushed new commits to it.

Adds sponsor attributions and styles to sponsored posts in the Posts Inserter. Also allows toggling on and off of sponsored posts.

Closes `1205103340481511/1203366842368233`.

#### Sponsor attributions and styles

1. Check out this branch and https://github.com/Automattic/newspack-sponsors/pull/263.
2. Create a native sponsor using Newspack Sponsors and assign it directly to a post. Also create a second native sponsor and assign it to a category or tag.
3. Create a newsletter and add a Posts Inserter block. Set the query controls to display the sponsored post and category/tag.
4. Confirm that the sponsored post and any posts in the sponsored category/tag appear in the preview with their sponsor flag and attribution. Note that the sponsor logo isn't shown because for some reason, the post editor had a really hard time rendering the image in the preview. We can look into adding the logos in a future PR if we really need them.

Screenshot 2023-08-28 at 4 44 10 PM

5. Insert the posts and then send the email. Confirm that the flag and attribution appear with the sponsored posts in the sent email as well.
6. Play with different sponsor settings such as changing the color of the flag in the Customizer, changing the attribution text in the sponsor's settings, and setting override settings in the sponsored post itself. Try adding multiple sponsors to a single post. Confirm that the various settings are displayed as expected in the Posts Inserter.

#### Show/hide sponsored posts

1. Create a newsletter and add a Posts Inserter block. In the block settings, confirm there's a new toggle to display sponsored posts, on by default:

Screenshot 2023-08-28 at 5 35 04 PM

2. Toggle off the setting and confirm that the results shown don't include any sponsored posts—both posts with sponsors directly assigned, and posts in a sponsored category/tag.

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by leogermani** [comment]
I found a couple of possible issues

I noticed that the font rendered for the "Sponsored" label looks different than the other fonts, and also different from the font that is rendered on the post on the site's front end.

The different font appears both on the Editor and on the sent email:

image

> Show/hide sponsored posts

I'm not sure what the expected behavior is, but this is what I see:

* If this is toggled ON, sponsored posts will show up at the top of the list, even if they are older posts.
* If this is toggled OFF, sponsored posts will not be prioritized, but if the most recent posts happen to be a sponsored post, it will be displayed. (It does not hide sponsored posts).

Is it the expected behavior? If so, I think we can explain it better

**Comment by dkoo** [comment]
> If this is toggled ON, sponsored posts will show up at the top of the list, even if they are older posts.

Hmm, this is not the expected behavior, nor is it what I'm seeing on my local site. When the "Display sponsored posts" toggle is ON (default state), I see sponsored posts in the Posts Inserter preview in the expected order. On my local site, I have four posts in the "Entertainment" category, one of them sponsored. The post shows up in the same order as on the front-end archive page:

Screenshot 2023-09-01 at 12 11 50 PM

> If this is toggled OFF, sponsored posts will not be prioritized, but if the most recent posts happen to be a sponsored post, it will be displayed. (It does not hide sponsored posts).

I think I know what's happening here. When the toggle is OFF, it simply adds a `tax_query` arg to the WP_Query to only get posts without the Sponsors taxonomy. But some posts can be shown as sponsored if they share a tag or category with a sponsor. Do your test sponsors have categories or tags applied? I'll work on a fix.

**Comment by leogermani** [comment]
> Do your test sponsors have categories or tags applied? I'll work on a fix.

Yes, it's a sponsorship added to a category, and the Posts Inserter doesn't have any filters applied

**Comment by dkoo** [comment]
@leogermani (if you get to this, otherwise I'll reassign to Miguel):

> I noticed that the font rendered for the "Sponsored" label looks different than the other fonts, and also different from the font that is rendered on the post on the site's front end.

f9e6a14 changes the sponsor flag element so that it uses a heading block at level 6 instead of a paragraph block. This makes the flag's font match the title's:

Screenshot 2023-09-01 at 2 18 05 PM

> Yes, it's a sponsorship added to a category, and the Posts Inserter doesn't have any filters applied

5438e3b also excludes any posts that have a sponsored category or tag from the query if "Display sponsored posts" is toggled off. To do this, I added a helper function in the Sponsors plugin in https://github.com/Automattic/newspack-sponsors/pull/263, so make sure to check out that branch before re-testing. Also updated testing instructions above.

**Review by leogermani — COMMENTED** [review]
It all works now. I don't see the issue with the order I saw the other time, I think this was my mistake.

But doing the tests, I got to a point where I was seeing this error:

```
PHP Fatal error:  Uncaught TypeError: array_map(): Argument #1 ($callback) must be a valid callback, class "category" not found in /newspack-repos/newspack-sponsors/includes/theme-helpers.php:375
```

and the block was not loading the contents anymore.

Here's what I did to get to this point:

* Created 2 sponsors, and assigned one to a category
* Manually assigned a post to the other sponsor. This post was one of the oldest posts I had
* Inserted the block and configured it to filter by the category of that post and to display 30 posts so I could see it in the list
* switched the toggle off

**Comment by dkoo** [comment]
Ugh, I made the mistake I always do and forget the order of args in `array_map`. 5a47547 should fix this.

**Comment by leogermani** [comment]
> Ugh, I made the mistake I always do and forget the order of args in array_map.

tests! :)

**Review by leogermani — APPROVED** [review]

**Pull request merged**
