### PR TITLE
feat(constant-contact): improved oauth flow

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR is a part of #1023 and fixes an issue with the provider's refresh token.

To obtain a refresh token - so the access token can be seamlessly updated - the API is missing an `offline_access` scope.  The OAuth flow is improved so that it can also be performed on the plugin's settings page:

image

### How to test the changes in this Pull Request:

1. Set your ESP to Constant Contact with valid API credentials
2. Make sure to delete these WP options: `newspack_newsletters_constant_contact_api_access_token`, `newspack_newsletters_constant_contact_api_refresh_token`
3. Visit the plugin's settings page
4. Confirm you see the notice on top of the form
5. Click to Authorize and go through with the flow (it may authorize automatically if the app was already previously authorized)
6. Confirm the page is refreshed and the subscription lists are rendered
7. Confirm that both WP options mentioned above exist in the database

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by leogermani — APPROVED** [review]
Works well!

Where are we documenting how to set up the Application on Constant Contact and what redirect URI to set up? This needs to be documented somewhere in the plugin.

Bonus: It would be awesome if we could trigger a page refresh after the authorization

**Comment by leogermani** [comment]
Ah, and I'd check the copy with a native speaker. Maybe you can drop the comma... or add a "In order to... " at the beginning

**Comment by miguelpeixe** [comment]
> Where are we documenting how to set up the Application on Constant Contact and what redirect URI to set up? This needs to be documented somewhere in the plugin.

Probably best on our site's support page.

> Bonus: It would be awesome if we could trigger a page refresh after the authorization

It does refresh the page

**Comment by miguelpeixe** [comment]
a72dee57c928a2dcc24e0294d349117e009491be adds provider names and updates the copy:

image

**Review by leogermani — APPROVED** [review]

**Pull request merged**
