### PR TITLE
fix: dont html encode ampersands in subject

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/trunk/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Fixes a small issue where ampersands are HTML encoded in the Subject.

Not sure if there's a better way to do it. But it's weird because the only character that is being HTML encoded is the ampersand, so loading a library to html_decode everything looked unnecessary.

### How to test the changes in this Pull Request:

1. In `trunk` edit a newsletters
2. add a `&` to the title and see that `$amp;` is added to the Subject input in the Newsletter sidebar
3. Checkout this branch and do the same
4. See that `&` is preserved as is

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by dkoo — CHANGES_REQUESTED** [review]
@leogermani this didn't work for me for some reason—the ampersands were still coming in as `&amp;` in the the subject text input when editing the post title field, and when synced to the ESP the subject still contained `&amp;`. I think WP converts certain characters into HTML entities when the strings are saved into the DB.

Here's what I had to do to fix the issue: https://github.com/Automattic/newspack-newsletters/pull/1687

This doesn't try to save the title with unescaped characters, it just displays the unescaped string in the sidebar field, and then decodes the HTML entities in the sync payload that gets sent to the ESP. Let me know what you think!

**Comment by leogermani** [comment]
@dkoo Your PR looks much more robust! Feel free to take it over!

**Comment by dkoo** [comment]
@leogermani I've merged #1687 into this PR. Paging @Automattic/newspack-product for another review!

**Comment by leogermani** [comment]
Works for me!

**Review by dkoo — APPROVED** [review]
🥸 PR approved, @dkoo!

**Pull request merged**
