### PR TITLE
feat: add support for embed

### LINKED ISSUE #386: Support embeds
Some embeds, like video, don't translate well to emails. A solution might be to produce a screenshot of an embed, and insert is as an image linking to the original embed.

### PR DESCRIPTION
**Pull request by miguelpeixe**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

Add support for the embed block. There are 4 types of embeddable content, as [specified on oEmbed](https://oembed.com/). For each available type we'll have the following behavior:

#### Video

Displays thumbnail with caption, which is the video title by default or the inline caption manually inserted. If no thumbnail is provided by the service, attempts to create a link with the title or caption.

#### Image

Displays image with caption, which is the image title by default or the inline caption manually inserted.

#### Rich

Validates HTML content, allowing `blockquote`, `p`, `a`, `br`, `em` and `strong`. If no valid HTML is returned after filtering, a link is generated with the resource title.

Examples are:

 - Twitter: returns a `blockquote`, which renders nicely
 - Amazon: returns an `iframe`, which becomes a link with the resource title

#### Link

Displays text with a link. The text is the resource title by default, or the inline caption manually inserted. I was not able to find a valid oembed provider that uses link as type but should work without problems.

Closes #386.

### How to test the changes in this Pull Request:

1. In this branch, create a new newsletter
2. Create several embed blocks with content from different services:
   1. YouTube
   2. Vimeo
   3. VideoPress
   3. Twitter
   4. Amazon
   5. Flickr
   6. Reddit
3. Send a test email and make sure the content is displayed as described above for each embed type

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Review by adekbadek — COMMENTED** [review]
Apart from `video` and `photo` types, the embeds are most likely to look much different in editor vs. in the email. WDYT about making it more WYSIWYG and displaying the embeds in the editor as they will appear in the email?

**Comment by miguelpeixe** [comment]
Good idea! I spent some time experimenting with different possibilities and I think we have 2 options to better integrate the WYSIWYG aspect:

 - Create a new custom block that makes use of the already implemented oEmbed API so the WYSIWYG also reflects the web output for published newsletters.
 - Modify how the current `core/embed` block displays the email result but maintain rich embeds for the published web version.

What do you think?

**Comment by adekbadek** [comment]
> Modify how the current core/embed block displays the email result but maintain rich embeds for the published web version.

This sounds like the best solution, maintaining WYSIWYG while enriching the public version.

**Comment by miguelpeixe** [comment]
Agreed! The email preview has been implemented with new toolbar buttons so the user can switch between email and web previews:

https://user-images.githubusercontent.com/820752/132248704-743f7c15-8b87-428e-9af6-0dc8a749e9df.mov

**Review by adekbadek — APPROVED** [review]
Great idea with the preview mode!

**Pull request merged**
