### PR TITLE
fix: do not auto subscribe to premium lists

### PR DESCRIPTION
**Pull request by leogermani**
### All Submissions:

* [x] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### Changes proposed in this Pull Request:

This PR changes the behavior of Newsletters and Woo Memberships integration, aka Premium Newsletters.

Before this PR, when a user was granted with a Membership, they were automatically subscribed to all Lists that were locked behind that plan.

After this PR, they will no longer be automatically subscribed. Editor will then be able to offer the premium lists and only members of that plan will see them.

Also, it prevents a Fatal from throwing in an edge case when removing readers from lists.

### How to test the changes in this Pull Request:

1. Set up a Premium Newsletter behind a Membership that requires a product (see instructions at PCYsg-SZM-p2) 
2. Set up a checkout button to the product associated to the Membership plan
3. As an anonymous reader, buy the plan.
4. Confirm in the ESP that the reader was not added to the premium list
5. verify the reader`s account
6. Go to My Account -> Newsletters and confirm you can see the premium list listed there and you are able to subscribe
7. Confirm in the ESP that the subscription worked
8. As an admin, revoke the reader`s membership
9. In the ESP, confirm the user was removed from the Premium list

Also test with Subscription on the checkou modal

11. Add `define( 'NEWSPACK_ENABLE_POST_CHECKOUT_NEWSLETTER_SIGNUP', true );` to you wp-config
12. As a new anonymous reader, buy the plan via the checkout modal
13. Confirm that in the Thank you message, you can see the Premium listed offered for subscription
14. In the ESP confirm the reader was not added to the premium list until they opt-in

New tests after last commit

15. Checkout https://github.com/Automattic/newspack-plugin/pull/2778
16. Repeat steps 12 to 14 and confirm they still work
17. Now do the same thing but buying a product that will NOT grant you the membership
18. Confirm that in the checkout modal, the premium list is filtered out and does not show up

### Other information:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new tests for your changes, as applicable?
* [x] Have you successfully ran tests with your changes locally?

### CODE REVIEW

**Comment by yogeshbeniwal** [comment]
> and only members of that plan will see them

Showing premium lists to all readers, but disabled for signup for users who are not member, will be better option at places like account section to encourage membership purchase.

**Comment by leogermani** [comment]
> > and only members of that plan will see them
> 
> Showing premium lists to all readers, but disabled for signup for users who are not member, will be better option at places like account section to encourage membership purchase.

I think this will vary a lot depending on the publisher, their strategy and also the number of lists they have.

In any case, this leaves the room open for them to publicize their premium offers via blocks wherever they want.

**Review by miguelpeixe — APPROVED** [review]
Is this meant to be a hotfix? It's set to master.

**Comment by leogermani** [comment]
Thanks @miguelpeixe . I'm gonna hold this hotfix for next week, so a refresh might be needed

**Comment by leogermani** [comment]
@miguelpeixe I found an issue and updated the PR. Updated the test instructions with new tests (from 15 on)

**Comment by adekbadek** [comment]
@leogermani – what's the status here? Should it still be released as a hotfix?

**Comment by leogermani** [comment]
@adekbadek No, we are holding this.

Details -> pamTN9-8ig-p2#comment-9821

I'm gonna close the PR for now. https://github.com/Automattic/newspack-newsletters/pull/1377 changes this part of the code and this will have to be redone anyways if we decide to make this change in the future

**Pull request closed without merging**
